"""Initial schema

Revision ID: 00cdb2a86b98
Revises: 
Create Date: 2026-04-29 16:27:59.118599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00cdb2a86b98'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scheme_updates_id'), table_name='scheme_updates')
    op.drop_index(op.f('ix_scheme_updates_title'), table_name='scheme_updates')
    op.drop_table('scheme_updates')
    op.drop_index(op.f('ix_shared_chats_id'), table_name='shared_chats')
    op.drop_index(op.f('ix_shared_chats_share_token'), table_name='shared_chats')
    op.drop_table('shared_chats')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shared_chats',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.INTEGER(), nullable=True),
    sa.Column('share_token', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('expires_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shared_chats_share_token'), 'shared_chats', ['share_token'], unique=1)
    op.create_index(op.f('ix_shared_chats_id'), 'shared_chats', ['id'], unique=False)
    op.create_table('scheme_updates',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('scheme_id', sa.INTEGER(), nullable=True),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('ministry', sa.VARCHAR(), nullable=True),
    sa.Column('url', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('detected_at', sa.DATETIME(), nullable=True),
    sa.Column('source', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheme_updates_title'), 'scheme_updates', ['title'], unique=False)
    op.create_index(op.f('ix_scheme_updates_id'), 'scheme_updates', ['id'], unique=False)
    # ### end Alembic commands ###
